jenkins:
    systemMessage: "Serverless Jenkins on Amazon Fargate"
    numExecutors: 0
    remotingSecurity:
      enabled: true
    agentProtocols:
        - "JNLP4-connect"
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: admin
                  password: ${ADMIN_PWD}
    authorizationStrategy:
        globalMatrix:
            grantedPermissions:
                - "Overall/Read:authenticated"
                - "Job/Read:authenticated"
                - "View/Read:authenticated"
                - "Overall/Administer:authenticated"
    crumbIssuer: "standard"
    slaveAgentPort: 50000
    clouds:
        - ecs:
              numExecutors: 1
              allowedOverrides: "inheritFrom,label,memory,cpu,image"
              credentialsId: ""
              cluster: arn:aws:ecs:us-west-2:090334723359:cluster/jenkins-agents
              name: "fargate-cloud-agents"
              regionName: us-west-2
              retentionTimeout: 10
              jenkinsUrl: "http://controller.jenkins:8080"
              templates:
                  - cpu: 512
                    assignPublicIp: true
                    image: "jenkins/inbound-agent"
                    label: "agent-builder"
                    executionRole: arn:aws:iam::090334723359:role/jenkins-ecs-execution-role
                    launchType: "FARGATE"
                    memory: 0
                    memoryReservation: 1024
                    networkMode: "awsvpc"
                    privileged: false
                    remoteFSRoot: "/home/jenkins"
                    securityGroups: sg-0a6fdf5a1c7686737
                    sharedMemorySize: 0
                    subnets: subnet-0a68ccafccaa2c745
                    templateName: "agent-builder"
                    uniqueRemoteFSRoot: false
security:
  sSHD:
    port: -1
jobs:
  - script: >
      pipelineJob('Example job task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'agent-builder'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on a fargate agent instance"
                            }
                            sh 'sleep 20'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
